export {default as mkHandler} from './mkHandler'
export {default as mkHandlers} from './mkHandlers'
export {default as logRequestError} from './logRequestError'
export {default as logRequestErrorAndFail} from './logRequestErrorAndFail'
export {default as buildLocalePageCodes} from './buildLocalePageCodes'
export {default as getLegacyOrientationPrefixes} from './getLegacyOrientationPrefixes'
export {default as deepFreeze} from './deepFreeze'
